magni_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    cmd_vel_timeout: 0.25

    enable_odom_tf: true

    wheel_separation : 0.33
    wheel_radius : 0.1015

    wheel_separation_multiplier: 1.0 # default: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
    twist_covariance_diagonal: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2]

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.0   # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.1   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 5.0   # rad/s^2

motor_diagnostics_broadcaster:
  ros__parameters:
    battery_voltage_low_level: 23.2
    battery_voltage_critical: 22.5

controller_manager:
  ros__parameters:
    update_rate: 20  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    motor_diagnostics_broadcaster:
      type: ubiquity_motor/UbiquityMotorDiagnosticsBroadcaster

    magni_base_controller:
      type: diff_drive_controller/DiffDriveController